### ISSUE TITLE
replace repr() with .decode in all detectors, event handlers and input components.

### ISSUE THREAD

**Issue by dITySoftware** [ait-aecid/logdata-anomaly-miner#596] opened 2021-03-30 13:28 UTC

**Comment by landauermax** [comment] 2021-03-30 13:38
The purpose is to handle special characters (such as ä, ö, ü, ß) correctly. Please also add a test case (I think it fits in the demo) where (i) logs with special characters are read from file as new values and are also stored in the persistency, and (ii) a parser where special characters are used (e.g., in a FixedDataModelElement).

**Comment by landauermax** [comment] 2021-04-08 07:12
I don't think the current pull request goes in the right direction of resolving this issue. First of all, it is not just the log_atom.raw_data that is affected, also the match_value.decode() throws errors if special characters are involved (e.g., a new detected value by the value detector contains "ü"). Second, using try-except and falling back to repr() does not address the problem, since the output will be something like:

```
>>> repr("ü".encode())
"b'\\xc3\\xbc'"
```

While it is fine to have the \\xc3\\xbc in the output (with output i mean both what is printed on console and part of the resulting json as well as what is persisted), it is strange to have the b'...' in the string.

Also, testing echo `"Any:äöüß" >> /tmp/syslog` is not sufficient, since the problem also concerns the encoding of the file. So it should be tested once with a file encoded in utf-8 and once in latin-1.

I propse the following solution: We introduce a parameter in the config.yml that allows the set the encoding of the file, e.g., ENCODING = 'utf-8' by default (which should be the correct encoding for almost all log files). Then, all .decode() in the detectors and output components should be used with this encoding from the aminerConfig.

**Comment by dITySoftware** [comment] 2021-04-08 07:42
I have changed every occurrence of repr() where it is clear that the data has the bytes type. Most of the skips happened in the VTD and VCD.  With match_value you are right, I have to recheck that.

Can you suggest me a better fallback solution than using repr(), without running into new exceptions? I think repr() is the safest way to guarantee that the aminer does not stop working, because of encoding errors. b'..' is the way bytes are represented. I can not change that.

I do not agree with the idea of having the encoding configurable. How would that work with multiple files having different encodings? It is much easier to change the encoding of the file to utf-8. Also it is not possible (at least not reliably) to automatically determine the encoding of a file. We should clearly document that files must be encoded utf-8.
This would just be another source of errors which can easily be avoided.

Also `"Any:äöüß"` does actually work with .decode(). The try-except was only used to guarantee the functionality of the aminer in any case possible - even when .decode() fails.

**Comment by landauermax** [comment] 2021-04-08 08:43
I do not have a better fallback than repr(), but I want to avoid that it is necessary to call repr() as good as possible. Unfortunately it is not always possible to change the encoding of the log files. Logs are just generated in a certain way, and we should try to support them in whatever way they come.

I know that having multiple files is problematic, but having an encoding parameter is at least a start. If we run into the problem that we have multiple files of different encodings at the same time, we can still add a file-dependent encoding parameter as well - but I think this is unlikely to occur. Also, I agree that automatically determining the file encoding is not reasonable and therefore this parameter should only be set by users manually in the config if necessary. Anyway, the parameter is just optional and having it does not hurt.

I know that `"Any:äöüß"` works with .decode(), but only when the file is written in utf-8. If the file is written in latin-1 (and then read as bytes, as the aminer does), it will not work. The result will be like this:

```
>>> "ü".encode('latin-1').decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 0: invalid start byte
```

**Comment by dITySoftware** [comment] 2021-04-08 09:23
Well it is not as easy. If we implement such parameter we really have to change code in every part of the aminer. Every .decode() call has to be changed to use the encoding parameter. This is however also necessary if we do not use the parameter.. (using try-except). But there might be unexpected errors that can occur from changing the encoding.

The second case is handled by the exception block and which then returns the repr() of the data, so the aminer actually does not stop working.

Also what happens if the encoding is not installed on the system?
I still think the drawbacks overweight the benefit of having a clear output of other encodings for special characters..

At the time of writing I got the idea to convert the data if the encoding parameter is used. So for example the SimpleByteStreamLineAtomizer can convert the data from latin-1 to utf-8. This would need the least amount of changes in code.

I would still leave the try-except construct, just in case something goes wrong. What do you think of this idea?

**Comment by landauermax** [comment] 2021-04-08 09:53
We do not have to change the decodes that do not handle anything other than the logs, for example, i think we also decode file paths. As you say, it is more or less the same as for the current changes using try-except.

I know that the aminer does not stop working, I just wanted to point out that decode without encoding does not work for latin-1 files that contain special characters. And calling repr() by default on these files is not a good solution, especially since it is only called on those lines and tokens that contain special characters, creating inconsistencies in the output.

If the user selects an encoding that is not installed, that is their problem. They need to take care of that.

I would not like conversion in the Atomizer. We decided to use bytes for handling logs within the aminer to avoid any problems with special characters - and this works well. Changing anything would just introduce a new complexity that is not necessary at this point. The issue is only about how to represent the anomalies, i.e., the output. And even if we read in the bytes in a specific encoding, we still need to use the same encoding in the output. 

The try-except is okay as a fallback, but should only take effect if the wrong encoding is used.

**Comment by dITySoftware** [comment] 2021-04-08 09:56
Okay, everything is clear. I will implement this solution.

**Comment by dITySoftware** [comment] 2021-04-12 05:49
The config can not be applied to the SimpleUnparsedAtomHandler and VerboseUnparsedAtomHandler, because they do not have the aminer config.

**Comment by dITySoftware** [comment] 2021-04-12 05:51
Also it is not possible in any of the parsing components.

**Comment by landauermax** [comment] 2021-04-12 07:00
It should not be necessary in the parsing components. Most of the operations in the parsing elements work with bytes just as with strings, e.g., re.search and re.escape in the DelimitedDataModelElement should work on bytes and strings in the same way. In model elements like the Hex or Base64 elements we know anyway that the characters must be in utf-8. 

In the Simple and Verbose Unparsed Handlers, I think there is no problem adding the aminer config as a parameter, like it is done for the detectors.

**Comment by dITySoftware** [comment] 2021-04-12 07:12
Do we really know if the decoded string in the Base64 handler is utf-8? I think it is possible to encode data with all encodings to base64.

However, I have found an way around the import problem and now it is possible to use the ENCODING constant in all aminer classes, including parsers.

**Comment by landauermax** [comment] 2021-04-12 07:44
Yes that is true, I was not aware that there is a .decode() in the Base64 element. The comment says `# we need to check if no exception is raised when decoding the original string.` but I do not remember why it is necessary to do this check, I would have thought that as long as it can be decoded, it is fine.

Anyway, if there is a workaround to get the encoding in there, then it should not be a problem anyway.

**Comment by dITySoftware** [comment] 2021-04-12 07:56
After all the reason why base64 is used, is to encode non-printable characters to printable characters. So if we try to decode this base64 string and some characters are non-printable, we get an exception. In that case we just want to return the base64 encoded string as match_object.

**Closed** 2021-07-09 11:07 UTC
Labels: bug
