### ISSUE TITLE
error when passing abolute config path

### ISSUE THREAD

**Issue by viktorbeck98** [ait-aecid/logdata-anomaly-miner#1371] opened 2024-11-19 15:34 UTC
For some reason i get this error when is use the absolute path instead of the relative path:

![grafik](https://github.com/user-attachments/assets/df8590b8-2a00-43fe-acc5-5b1c13765219)

**Comment by viktorbeck98** [comment] 2024-11-19 15:35
However, it seems to somehow processs the file because an empty file (test.yaml) in the same location gives:

(env) beckv@N3DSS2438:~/projects/AIT/aminer-configuration-engine$ sudo aminer -o -c /home/beckv/projects/AIT/aminer-configuration-engine/test.yaml
(<class 'cerberus.validator.DocumentError'>, DocumentError('document is missing'), <traceback object at 0x7f50bf20fa80>)
Traceback (most recent call last):
  File "/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py", line 78, in load_config
    aminer_config.load_yaml(yaml_config)
  File "/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py", line 70, in load_yaml
    if not v.validate(yaml_data, validation_schema):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/aminer/conf-enabled/cerberus/validator.py", line 1031, in validate
    self.__init_processing(document, schema)
  File "/etc/aminer/conf-enabled/cerberus/validator.py", line 644, in __init_processing
    raise DocumentError(errors.DOCUMENT_MISSING)
cerberus.validator.DocumentError: document is missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aminer", line 788, in <module>
    main()
  File "/usr/bin/aminer", line 338, in main
    aminer_config = AminerConfig.load_config(config_file_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py", line 88, in load_config
    raise Exception(exception_info[0], exception_info[1], exception_info[2])
Exception: (<class 'cerberus.validator.DocumentError'>, DocumentError('document is missing'), <traceback object at 0x7f50bf20fa80>)

**Comment by ernstleierzopf** [comment] 2024-11-25 14:56
@viktorbeck98 I could not reproduce this issue on my machine. I see that you use a virtual environment. I don't use one myself, but it might be something in it causing the issue.

Could you please describe me:
- how exactly the was the virtual environment created
- which system is used
- how was aminer installed?

**Comment by ernstleierzopf** [comment] 2024-11-25 15:42
hmm I don't have any experience with WSL.. could you please call `pwd` and `ls -la` so I can get maybe get an idea of the issue?

**Comment by ernstleierzopf** [comment] 2024-11-25 15:52
try following: `python3 -c "import os; print(os.path.exists('config.yaml')); print(os.path.exists('~/projects/AIT/aminer-configuration-engine/config.yaml')); print(os.path.exists('/home/vbeck/projects/AIT/aminer-configuration-engine/config.yaml')`

try `wslpath ~` or `wslpath /home/vbeck/projects/AIT/aminer-configuration-engine/config.yaml` and use the resulting file in the above script to check if it can be found.

**Comment by viktorbeck98** [comment] 2024-11-25 16:23
Like this? :)

![grafik](https://github.com/user-attachments/assets/983cbb17-26d9-4114-bf88-9a109c432587)

**Comment by ernstleierzopf** [comment] 2024-11-25 16:31
yes, could you now try wslpath with the -w option?

**Comment by ernstleierzopf** [comment] 2024-11-25 16:36
same as ~ path resolution does not work, there might be an issue with the real path of the WSL subsystem.

**Comment by ernstleierzopf** [comment] 2024-11-25 16:37
but I am not really sure, because the path was clearly found..

**Comment by ernstleierzopf** [comment] 2024-11-25 16:47
could you maybe print the output of /var/log/aminer/aminer.log after each call? Maybe we can see something there.

**Comment by ernstleierzopf** [comment] 2024-11-25 16:52
could you also please print the exit code after each call?

**Comment by ernstleierzopf** [comment] 2024-11-25 17:00
Maybe this is the issue? https://stackoverflow.com/questions/51278020/using-os-path-join-on-ubuntu-on-windows

> Try import os and/or import sys and check the values of os.platform and/or sys.executable, and also see that os.path is actually posixpath and not ntpath. – 
> [metatoaster](https://stackoverflow.com/users/2904896/metatoaster)
>  [CommentedJul 11, 2018 at 10:26](https://stackoverflow.com/questions/51278020/using-os-path-join-on-ubuntu-on-windows#comment89543372_51278020)

please try to find out if the actual Ubuntu version of python is running, not the Windows one as suggested in the thread.

If all of these infos do not help, I might need to setup my own WSL Ubuntu

**Comment by viktorbeck98** [comment] 2024-11-26 08:57
I am pretty sure its not a path problem. An empty file is recognized but when i paste (meaningful) content into the file i get "... not yet available":

![grafik](https://github.com/user-attachments/assets/12417cfe-9eeb-4135-b6ad-896d079a0b19)

 Also, if i delete some of the config file's essential parts i get an error, so the file is definetly recognized by the aminer:

![grafik](https://github.com/user-attachments/assets/1a57122e-9c9b-45c4-9364-14d64329ef8f)

Also, this problem did not occur on my old laptop...

**Comment by ernstleierzopf** [comment] 2024-11-26 09:05
okay, so this occurs only with a specific config, right? You can create a config which works with the absolute path?

Please post two things:
- config which fails posted with the code function on github for easy copy/paste
- exit code of the aminer for each run using the absolute and relative paths (echo $?)

**Comment by viktorbeck98** [comment] 2024-11-26 09:53
Here are the files
[example.zip](https://github.com/user-attachments/files/17917445/example.zip)

**Comment by ernstleierzopf** [comment] 2024-11-26 09:56
sorry my mistake, the correct directory of the log files is /var/lib/aminer/log, so we need the /var/lib/aminer/log/aminer.log file.
One interesting thing would be to know if the output.json is the same with the absolute path as with the relative path.

**Comment by viktorbeck98** [comment] 2024-11-26 10:15
Ok, now i get the following:
![grafik](https://github.com/user-attachments/assets/9c468974-042a-4efb-8e39-c1ee37b4f207)

No output file is generated when "not yet available" is returned...

**Comment by viktorbeck98** [comment] 2024-11-26 10:17
Are you able to reproduce the "not yet available"  error?

**Comment by ernstleierzopf** [comment] 2024-11-26 10:22
no I can not reproduce it.. WSL Linux seems to be somehow weird here. Please use virtualbox with a proper VM instead, as we do not really support the aminer in WSL.
We could discuss this in the group if we want to support wsl properly. @landauermax @whotwagner @4cti0nfi9ure 

Please reply here again if the error also occurrs in the VM.

**Comment by viktorbeck98** [comment] 2024-11-26 11:06
Hm that's weird ... it worked perfectly fine on my old machine (also with WSL). I'll look into it. Thanks for the help!

**Comment by ernstleierzopf** [comment] 2024-11-27 07:00
could you please get back to me after setting up the VM, if the error still persists or if it is gone?
Also if there is enough interest (needs to be discussed), we can support WSL with proper testing. But for the moment I think it is out of scope and no resources should be used for this.

**Closed** 2024-12-02 16:45 UTC
Labels: bug
