### ISSUE TITLE
Move classes from init files to separate files

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#83] opened 2020-07-13 08:30 UTC

**Comment by dITySoftware** [comment] 2020-09-24 07:35
I have researched this topic and most of the times classes are still imported in the init files.
Should every class import from it's main location? for example
from aminer.analysis.NewMatchPathValueComboDetector import NewMatchPathValueComboDetector
instead of 
from from aminer.analysis import NewMatchPathValueComboDetector

Or should all imports be done in a separate file (i.e. imports.py) and the separate file be imported in __init__.py?

**Comment by landauermax** [comment] 2020-09-25 06:04
The problem is that some classes are difficult to find when they are hidden in the init files. It may be common, but it is not recommended, see e.g. https://stackoverflow.com/questions/47740935/can-i-put-a-class-definition-into-init-py

**Comment by dITySoftware** [comment] 2020-09-25 07:12
fixed in PR #156.

**Closed** 2020-09-28 06:01 UTC
Labels: refactor
