### ISSUE TITLE
Fix import warnings

### ISSUE THREAD

**Issue by 4cti0nfi9ure** [ait-aecid/logdata-anomaly-miner#218] opened 2020-10-30 14:55 UTC
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__

  return f(*args, **kwds) 

should not occur, when running the aminer.

**Comment by dITySoftware** [comment] 2020-10-30 16:42
This is an known issue. It occurs because of an older version of scipy is being install from the dpkg repository. 
In the newer version of scipy installed with pip this warning does not occur.

There is an open PR in the aminer-ansible project which changes the installation from apt to pip and fixes this error. However @whotwagner does not want to run versions from pip as they are not supported like the versions from apt. Please discuss this with @whotwagner and approv or reject the open PR.

The second option is to wait until a newer version of scipy is pushed to the dpkg repository.

This issue is not related to the aminer and can not be fixed in it.

**Comment by whotwagner** [comment] 2020-11-02 09:25
We have to find a solution somehow. We should not rely on pip packages because we want the aminer in the debian package repository. That means: all packages have to be installed via debian-packages.
If we are not able to fix this bug in code, we should investigate it and create a bugreport for the debian maintainer of the python3-scipio package.

**Comment by whotwagner** [comment] 2020-11-02 09:25
Do we have that problem in Debian Bullseye too?

**Comment by dITySoftware** [comment] 2020-11-02 09:41
The problem is not dependent on the system used. It is purely in the scipy package.
I do not know if the problem exists in Debian Bullseye. However current versions of python offers python3-scipy 1.5.2-2 which is much newer than the ubuntu version. So this issue might have been solved there.

Also there currently seems to be no working version of cerberus and kafka (the further needs to be in version 2.xx, however in dpkg 1.xx is offered)

We could ignore the warning in code as it does not affect any of it and everything is just working fine.

**Comment by whotwagner** [comment] 2020-11-02 09:48
I know that the problem is not dependent on the system but on the scipy package. However in Debian Bullseye there is a newer python3-scripy package. Therefore we should test if the warnings still occur in Debian Bullseye. 

I'll create a seperate issue of the kafka-packages-problem...

**Comment by dITySoftware** [comment] 2020-11-02 09:54
As I can remember none of the warnings occured when testing as i did not redirect stderr to a file. However I am also not 100% sure any more..

**Comment by dITySoftware** [comment] 2020-11-02 09:54
What would be the solution IF the warnings occured?

**Comment by whotwagner** [comment] 2020-11-02 09:56
If these problems occur even with the python3-scipy packages, we have to figure out the source of the problem and file a bugreport for the python3-scipy maintainers. Or fix the problem in our code if it is possible to fix it.

**Comment by dITySoftware** [comment] 2020-11-02 10:15
There already existed an Issue in scipy: https://github.com/scipy/scipy/issues/11000
What happened was that they referred to a newer version and closed the issue. I actually think they just ignore the warning in the code with a filter.

**Comment by dITySoftware** [comment] 2020-11-04 13:31
This issue seems to be related to python version 3.6. When testing #220 with all packages from dpkg this warning never occurred!

**Comment by dITySoftware** [comment] 2020-11-04 13:32
Please try changing python to version 3.8

**Comment by dITySoftware** [comment] 2020-11-04 14:22
Other possible error source is the used system. This error occurs in Ubuntu 18.04. Ubuntu 20.04 and Debian Bullseye work without this error (however using python3.8)

**Comment by dITySoftware** [comment] 2020-11-13 09:38
Please decide how this problem should be solved.
There are three options:

1. Ignore the warning in code
2. Ignore the warning by changing the installation configs in Travis (preferred by me)
3. Wait until the warning is solved by installing newer versions of packages.

**Comment by landauermax** [comment] 2020-11-13 11:13
@whotwagner please comment on this.

**Comment by dITySoftware** [comment] 2020-11-13 13:16
Option 1 will be implemented.

**Closed** 2020-12-18 15:35 UTC
Labels: bug
